# Logging
logging:
  config: classpath:logback-console.xml

# Spring PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tech1_b2b_postgres_server
    username: postgres
    password: postgres
  jpa:
    show-sql: true

# Tech1 Platform
tech1:
  serverConfigs:
    webclientURL: http://localhost:3000
  incidentConfigs:
    enabled: true
    remoteServer:
      baseURL: http://localhost:8973
      username: admin
      password: admin
  mvcConfigs:
    corsConfigs:
      allowedOrigins:
        - http://localhost:8686
        - http://localhost:8787

