# Logging
logging:
  config: classpath:logback-console.xml

# Spring PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tech1_b2b_postgres_server
    username: postgres
    password: postgres
  jpa:
    show-sql: true

# Tech1 Framework
tech1:
  serverConfigs:
    webclientURL: http://localhost:3000
  utilitiesConfigs:
    geoLocationsConfigs:
      geoLiteCityDatabaseEnabled: false
    geoCountryFlagsConfigs:
      enabled: false
    userAgentConfigs:
      enabled: false
  incidentConfigs:
    enabled: true
    remoteServer:
      baseURL: http://localhost:8973
      credentials:
        username: admin
        password: admin
  mvcConfigs:
    corsConfigs:
      allowedOrigins:
        - http://localhost:8686
        - http://localhost:8787
  securityJwtConfigs:
    cookiesConfigs:
      domain: localhost
    incidentsConfigs:
      typesConfigs:
        AUTHENTICATION_LOGIN: true
        AUTHENTICATION_LOGIN_FAILURE_USERNAME_PASSWORD: false
        AUTHENTICATION_LOGIN_FAILURE_USERNAME_MASKED_PASSWORD: true
        AUTHENTICATION_LOGOUT: false
        AUTHENTICATION_LOGOUT_MIN: false
        SESSION_REFRESHED: true
        SESSION_EXPIRED: false
        REGISTER1: true
        REGISTER1_FAILURE: true
    jwtTokensConfigs:
      secretKey: ENC(G/ikUUQcuS4+pbN4dj1gPlGwm/Ht2a+8)
      storageMethod: COOKIES
      accessToken:
        expiration:
          amount: 30
          unit: SECONDS # @java.time.temporal.ChronoUnit
      refreshToken:
        expiration:
          amount: 60
          unit: SECONDS # @java.time.temporal.ChronoUnit
    loggingConfigs:
      advancedRequestLoggingEnabled: false
    sessionConfigs:
      cleanSessionsByExpiredRefreshTokensCron:
        enabled: true
        expression: "*/30 * * * * *"
        zoneId: "Europe/Kyiv"
      enableSessionsMetadataRenewCron:
        enabled: true
        expression: "*/30 * * * * *"
        zoneId: "Europe/Kyiv"
    essenceConfigs:
      defaultUsers:
        enabled: true
        users:
          - username: admin11
            password: "$2a$11$qzm4DlVWEssSavOV0Qf0JOzxQZPIlwl8ja5KlQmBn2QtK7G7bSx3C"
            zoneId: "Europe/Kyiv"
            passwordChangeRequired: false
            authorities: [ "admin", "invitationCode:write" ]
      invitationCodes:
        enabled: true
