#file: noinspection SpringBootApplicationYaml
# Logging
logging:
  config: classpath:logback-console.xml

# jbst
jbst:
  email-configs:
    enabled: false
  server-configs:
    springdoc-enabled: true
    webclient-url: http://localhost:3000
  utilities-configs:
    geo-locations-configs:
      geo-lite-city-database-enabled: false
    geo-country-flags-configs:
      enabled: false
    user-agent-configs:
      enabled: false
  incident-configs:
    enabled: true
    remote-server:
      base-url: http://localhost:8973
      credentials:
        username: admin
        password: admin
  mvc-configs:
    cors-configs:
      allowed-origins:
        - http://localhost:3003
        - http://localhost:8686
        - http://localhost:8787
  security-jwt-configs:
    cookies-configs:
      domain: localhost
    incidents-configs:
      types-configs:
        AUTHENTICATION_LOGIN: true
        AUTHENTICATION_LOGIN_FAILURE_USERNAME_PASSWORD: false
        AUTHENTICATION_LOGIN_FAILURE_USERNAME_MASKED_PASSWORD: true
        AUTHENTICATION_LOGOUT: false
        AUTHENTICATION_LOGOUT_MIN: false
        SESSION_REFRESHED: true
        SESSION_EXPIRED: false
        REGISTER1: true
        REGISTER1_FAILURE: true
    jwt-tokens-configs:
      secret-key: ENC(GbnDNQVCspqW74HYwR6XePbdG6dmo7l/rIPe+hL7uHSnj+5kkUQsj0ZPegUGytLpx/5pdLO7vdQ=)
      storage-method: COOKIES
      access-token:
        expiration:
          amount: 30
          unit: MINUTES # @java.time.temporal.ChronoUnit
      refresh-token:
        expiration:
          amount: 60
          unit: MINUTES # @java.time.temporal.ChronoUnit
    logging-configs:
      advanced-request-logging-enabled: false
    session-configs:
      clean-sessions-by-expired-refresh-tokens-cron:
        enabled: false
        expression: "*/30 * * * * *"
        zone-id: "Europe/Kyiv"
      enable-sessions-metadata-renew-cron:
        enabled: false
        expression: "*/30 * * * * *"
        zone-id: "Europe/Kyiv"
    essence-configs:
      default-users:
        enabled: true
        users:
          - username: admin11
            password: "$2a$11$qzm4DlVWEssSavOV0Qf0JOzxQZPIlwl8ja5KlQmBn2QtK7G7bSx3C"
            zone-id: "Europe/Kyiv"
            password-change-required: false
            authorities: [ "admin", "invitations:write" ]
          - username: superadmin11
            password: "$2a$11$qzm4DlVWEssSavOV0Qf0JOzxQZPIlwl8ja5KlQmBn2QtK7G7bSx3C"
            zone-id: "Europe/Kyiv"
            password-change-required: false
            authorities: [ "superadmin", "invitations:read", "invitations:write" ]
      invitations:
        enabled: true
