#file: noinspection SpringBootApplicationYaml

# Spring PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:3004/jbst
    username: postgres
    password: postgres
  jpa:
    show-sql: false
