#file: noinspection SpringBootApplicationYaml
# Spring PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jbst_dev
    username: postgres
    password: postgres
  jpa:
    show-sql: true
