#file: noinspection SpringBootApplicationYaml
# Server
server:
  servlet:
    context-path: /api

# Spring Security: actuator endpoints (no security check)
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# Swagger
springdoc:
  swagger-ui:
    tags-sorter: "alpha"

# Tech1 Framework
tech1:
  maven-configs:
    group-id: @project.groupId@
    artifact-id: @project.artifactId@
    version: @project.version@
  async-configs:
    thread-name-prefix: tps1-async
    threadsCorePoolPercentage: 25
    threadsMaxPoolPercentage: 50
  events-configs:
    thread-name-prefix: tps1-events
    threadsCorePoolPercentage: 75
    threadsMaxPoolPercentage: 100
  mvc-configs:
    enabled: true
    framework-base-path-prefix: /framework/security
    cors-configs:
      path-pattern: /**
      allowed-methods:
        - DELETE
        - GET
        - POST
        - PUT
      allowed-headers:
        - Cache-Control
        - Content-Type
      allow-credentials: true
  hardware-monitoring-configs:
    enabled: true
    thresholds-configs:
      CPU: 80
      HEAP: 80
      SERVER: 85
      SWAP: 95
      VIRTUAL: 85
  security-jwt-configs:
    authorities-configs:
      authorities:
        - value: superadmin
        - value: user
        - value: admin
        - value: invitationCode:read
        - value: invitationCode:write
      package-name: tech1.framework.iam.server.base.domain.enums
    cookies-configs:
      jwt-access-token-cookie-creation-latency:
        unit: SECONDS
        amount: 5
    jwt-tokens-configs:
      access-token:
        cookie-key: ajwt
      refreshToken:
        cookie-key: rjwt
    users-emails-configs:
      subject-prefix: "[Tech1]"
      authentication-login:
        enabled: true
      session-refreshed:
        enabled: true
  security-jwt-websockets-configs:
    csrf-configs:
      header-name: "t-csrf-header"
      parameter-name: "_csrf"
      token-key: "t-csrf-token"
    stomp-configs:
      endpoint: "/t1f-iam-server-websockets"
    broker-configs:
      application-destination-prefix: "/app"
      simple-destination: "/queue"
      user-destination-prefix: "/user"
    template-configs:
      enabled: true
    features-configs:
      hardware-configs:
        enabled: true
        user-destination: "/accounts"
      reset-server-configs:
        enabled: true
        user-destination: "/accounts"

# Tech1 Server
tech1-server:
  server-configs:
    target-attribute1: "value1"
    target-attribute2: 10
    target-authority: "USER"

