#file: noinspection SpringBootApplicationYaml

# Spring Security: actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# jbst
jbst:
  server-configs:
    # omitted behaviour, no spring security, port-forwarding security
    springdoc-enabled: false
  maven-configs:
    group-id: @project.groupId@
    artifact-id: @project.artifactId@
    version: v@project.version@
  async-configs:
    thread-name-prefix: hms-async
    threadsCorePoolPercentage: 50
    threadsMaxPoolPercentage: 100
  events-configs:
    thread-name-prefix: hms-events
    threadsCorePoolPercentage: 25
    threadsMaxPoolPercentage: 50

