#file: noinspection SpringBootApplicationYaml

# Logging
logging:
  config: classpath:logback-console.xml

# jbst
jbst:
  server-configs:
    name: hms-dev
  hardware-server-configs:
    base-url: http://localhost:3002
