services:
  jbst-server:
    image: ghcr.io/tech1-agency/jbst-iam-server:1.5
    restart: unless-stopped
    container_name: jbst-server
    networks:
      - jbst-network
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SPRING_BOOT_PROFILE=mongodb
      - CONFIG_LOCATIONS=classpath:application.yml,classpath:application-dev.yml,classpath:application-mongo.yml,file:/application-docker-mongodb.yml
      - JASYPT_PASSWORD=JJJJBSTGH
      - JVM_ARGUMENTS=-Xmx5g --add-opens=java.base/java.time=ALL-UNNAMED
    volumes:
      - ./application-docker-mongodb.yml:/application-docker-mongodb.yml

  jbst-mongodb:
    image: mongo:6.0.15
    restart: always
    container_name: jbst-mongodb
    ports:
      - "3004:27017"
    networks:
      - jbst-network
    volumes:
      - jbst-mongodb-data:/data/db

networks:
  jbst-network:
    name: jbst-network
    driver: bridge

volumes:
  jbst-mongodb-data:
