services:
  jbst-mongodb:
    image: mongo:6.0.15
    restart: always
    container_name: jbst-mongodb
    ports:
      - "3004:27017"
    networks:
      - jbst-network
    volumes:
      - jbst_mongodb_data:/data/db

networks:
  jbst-network:
    name: jbst-network
    driver: bridge

volumes:
  jbst_mongodb_data:
