services:
  t1f-b2b-postgres-server:
    image: ghcr.io/tech1-io/tech1-framework-b2b-postgres-server:3.0.0
    restart: unless-stopped
    container_name: t1f-b2b-postgres-server
    networks:
      - t1f-network
    ports:
      - "3002:3002"
    depends_on:
      t1f-b2b-postgres:
        condition: service_healthy
    links:
      - t1f-b2b-postgres
    environment:
      - PORT=3002
      - CONFIG_LOCATIONS=classpath:application.yml,file:/application-docker.yml
      - JASYPT_PASSWORD=JJEPTECH1
      - JVM_ARGUMENTS=-Xmx5g --add-opens=java.base/java.time=ALL-UNNAMED
    volumes:
      - ./application-docker.yml:/application-docker.yml

  t1f-b2b-postgres:
    image: postgres:14.3
    restart: always
    container_name: t1f-b2b-postgres
    ports:
      - "5432:5432"
    networks:
      - t1f-network
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - t1f-b2b-postgres-data:/var/lib/postgresql/data
      - ./init-postgres-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  t1f-network:
    name: t1f-network
    driver: bridge

volumes:
  t1f-b2b-postgres-data:
