name: delete-packages

on:
  schedule:
    - cron: "30 3 * * SUN"
  workflow_dispatch:

env:
  PACKAGE_OWNER: 'tech1-io'
  CONTAINER_MIN_VERSION_TO_KEEP: 2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      job_status: ${{ steps.tech1_mails_v2.outputs.job_status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # package-type: container

      - name: Delete Container Package Untagged Versions [tech1-framework-b2b-postgres-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-b2b-postgres-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true

      - name: Delete Container Package [tech1-framework-b2b-postgres-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-b2b-postgres-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: ${{ env.CONTAINER_MIN_VERSION_TO_KEEP }}

      - name: Delete Container Package Untagged Versions [tech1-framework-b2b-mongodb-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-b2b-mongodb-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true

      - name: Delete Container Package [tech1-framework-b2b-mongodb-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-b2b-mongodb-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: ${{ env.CONTAINER_MIN_VERSION_TO_KEEP }}

      - name: Tech1 mails@v2 outputs
        if: always()
        id: tech1_mails_v2
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT

  mails:
    if: always()
    needs: [main]
    runs-on: ubuntu-latest
    steps:
      - name: Mails
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: '${{ needs.main.outputs.job_status }}: ${{ github.repository }} » ${{ github.ref_name }}, ${{ github.workflow }} # ${{ github.run_number }}'
          to: ${{ secrets.EMAILS_ADMINS }}
          from: Tech1 Ops
          html_body: |
            <b>CommitterId</b>: ${{ github.actor }}<br>
            <b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>
            <b>Changes</b>: https://github.com/${{ github.repository }}/commit/${{ github.sha }}<br>
            <b>Committer</b>: ${{ github.event.commits[0].committer.name }}<br>
            <b>Message</b>: ${{ github.event.commits[0].message }}<br>
