name: keep-order

on:
  schedule:
    - cron: "30 3 * * SUN"
  workflow_dispatch:

env:
  PACKAGE_OWNER: 'tech1-agency'
  RELEASES_AND_TAGS_TO_KEEP: 5
  CONTAINER_MIN_VERSION_TO_KEEP: 2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
    outputs:
      job_status: ${{ steps.tech1_mails_v2.outputs.job_status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Delete packages - package-type: container

      - name: Delete Container Package Untagged Versions [tech1-framework-iam-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-iam-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true

      - name: Delete Container Package [tech1-framework-iam-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'tech1-framework-iam-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: ${{ env.CONTAINER_MIN_VERSION_TO_KEEP }}

      # Delete releases and tags

      - name: Delete Releases and Tags
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: ${{ env.RELEASES_AND_TAGS_TO_KEEP }}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tech1 mails@v2 outputs
        if: always()
        id: tech1_mails_v2
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT

  mails:
    if: always()
    needs: [main]
    uses: tech1-agency/tech1-ops/.github/workflows/actions-gmail-v4-min.yml@main
    secrets: inherit
    with:
      to: ${{ vars.EMAILS_ADMINS }}
      previous_job_status: ${{ needs.main.outputs.job_status }}
