name: keep-order

on:
  schedule:
    - cron: "30 3 * * SUN"
  workflow_dispatch:

env:
  PACKAGE_OWNER: 'tech1-agency'
  KEEP_COUNT_RELEASES_AND_TAGS: 5
  KEEP_COUNT_CONTAINERS: 3
  KEEP_COUNT_MAVEN_PACKAGES: 3
  MAVEN_MIN_VERSION_TO_KEEP: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Delete packages - package-type: container

      - name: Delete Container Package Untagged Versions [jbst-iam-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'jbst-iam-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true

      - name: Delete Container Package [jbst-iam-server]
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'jbst-iam-server'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: ${{ env.KEEP_COUNT_CONTAINERS }}

      # Delete packages - package-type: maven

      - name: Delete Packages
        uses: actions/delete-package-versions@v5
        with:
          owner: ${{ env.PACKAGE_OWNER }}
          package-name: 'packages.jbst.jbst-hardware-monitoring-server'
          package-type: 'maven'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: ${{ env.KEEP_COUNT_MAVEN_PACKAGES }}

      # Delete releases and tags

      - name: Delete Releases and Tags
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: ${{ env.KEEP_COUNT_RELEASES_AND_TAGS }}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notifications
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: "${{ job.status }}: ${{ github.repository }} » ${{ github.ref_name }}, ${{ github.workflow }} # ${{ github.run_number }}"
          from: ${{ vars.SMTP_GMAIL_FROM }}
          html_body: "<b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: ${{ vars.EMAILS_ADMINS }}
