name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MAVEN_DEPLOYMENT_ENABLED: 'true'
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IAM_SERVER_IMAGE: tech1-agency/tech1-framework-iam-server
  DOCKER_VERSION: '3.0.10-SNAPSHOT'
  DOCKER_PUSH_ENABLED: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      job_status: ${{ steps.tech1_mails_v2.outputs.job_status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven [build]
        if: env.MAVEN_DEPLOYMENT_ENABLED == 'false'
        run: mvn clean install

      - name: Maven [github packages]
        if: env.MAVEN_DEPLOYMENT_ENABLED == 'true'
        run: |
          mvn clean install \
            -Ddeployment_github_username=${{ github.actor }} -Ddeployment_github_token=${{ secrets.GITHUB_TOKEN }} \
            -s github-tech1/m2-settings.xml deploy -Pgithub-tech1

      - name: Docker login
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker [iam-server]
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: |
          cd tech1-framework-iam-server
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IAM_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IAM_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }}

      - name: Tech1 mails@v2 outputs
        if: always()
        id: tech1_mails_v2
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT

  mails:
    if: always()
    needs: [main]
    uses: tech1-agency/tech1-ops/.github/workflows/actions-gmail-v4.yml@main
    secrets: inherit
    with:
      to: ${{ vars.EMAILS_ADMINS }}
      previous_job_status: ${{ needs.main.outputs.job_status }}
