#file: noinspection UndefinedAction
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MAVEN_DEPLOYMENT_ENABLED: 'true'
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IAM_SERVER_IMAGE: tech1-agency/jbst-iam-server
  DOCKER_VERSION: '1.3'
  DOCKER_PUSH_ENABLED: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Maven [settings]
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
                "id": "github-jbst",
                "username": "${{ vars.USERNAME_MAVEN_PACKAGES }}",
                "password": "${{ secrets.TOKEN_MAVEN_PACKAGES }}"
            }]

      - name: Maven [build]
        if: env.MAVEN_DEPLOYMENT_ENABLED == 'false'
        run: mvn clean install

      - name: Maven [github packages]
        if: env.MAVEN_DEPLOYMENT_ENABLED == 'true'
        run: mvn clean -DskipTests -Dmaven.test.skip deploy -Pgithub

      - name: Docker login
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker [iam-server]
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: |
          cd jbst-iam-server
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IAM_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IAM_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }}

      - name: Notifications
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: "${{ job.status }}: ${{ github.repository }} » ${{ github.ref_name }}, ${{ github.workflow }} # ${{ github.run_number }}"
          from: ${{ vars.SMTP_GMAIL_FROM }}
          html_body: "<b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: ${{ vars.EMAILS_ADMINS }}
