name: main

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_MONGODB_SERVER_IMAGE: tech1-io/tech1-framework-b2b-mongodb-server
  DOCKER_POSTGRES_SERVER_IMAGE: tech1-io/tech1-framework-b2b-postgres-server
  DOCKER_VERSION: '2.8.4-SNAPSHOT'
  DOCKER_PUSH_ENABLED: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      job_status: ${{ steps.tech1_mails_v2.outputs.job_status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: GitHub Packages
        run: |
          mvn clean install \
            -Ddeployment_github_username=${{ github.actor }} -Ddeployment_github_token=${{ secrets.GITHUB_TOKEN }} \
            -s release-github/m2-settings.xml deploy -Prelease-github

      - name: Docker login
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker [mongodb]
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: |
          cd tech1-framework-b2b-mongodb-server
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_MONGODB_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_MONGODB_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }}

      - name: Docker [postgres]
        if: env.DOCKER_PUSH_ENABLED == 'true'
        run: |
          cd tech1-framework-b2b-postgres-server
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_POSTGRES_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }} .
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_POSTGRES_SERVER_IMAGE }}:${{ env.DOCKER_VERSION }}

      - name: Tech1 mails@v2 outputs
        if: always()
        id: tech1_mails_v2
        run: echo "job_status=${{ job.status }}" >> $GITHUB_OUTPUT

  mails:
    if: always()
    needs: [main]
    runs-on: ubuntu-latest
    steps:
      - name: Mails
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: '${{ needs.main.outputs.job_status }}: ${{ github.repository }} » ${{ github.ref_name }}, ${{ github.workflow }} # ${{ github.run_number }}'
          to: ${{ secrets.EMAILS_ADMINS }}
          from: Tech1 Ops
          html_body: |
            <b>CommitterId</b>: ${{ github.actor }}<br>
            <b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>
            <b>Changes</b>: https://github.com/${{ github.repository }}/commit/${{ github.sha }}<br>
            <b>Committer</b>: ${{ github.event.commits[0].committer.name }}<br>
            <b>Message</b>: ${{ github.event.commits[0].message }}<br>
