name: pipeline

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

env:
  DOCKERHUB_ORG: tech1io
  MONGODB_DOCKERHUB_REPOSITORY: tech1-framework-b2b-mongodb-server
  POSTGRES_DOCKERHUB_REPOSITORY: tech1-framework-b2b-postgres-server

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.setvars.outputs.docker_tag }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "dev" || "${{github.ref}}" == "refs/heads/dev" ]]; then
            echo "::set-output name=docker_tag::dev"
          fi

          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=docker_tag::prod"
          fi

  pipeline:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven [dev]
        if: github.ref == 'refs/heads/dev'
        run: mvn clean install

      - name: Maven [main]
        if: github.ref == 'refs/heads/main'
        run: mvn clean install -Dmaven.test.skip -DskipTests -T 4

      - name: Sonar
        if: github.ref == 'refs/heads/dev'
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN

      - name: Docker [Mongo]
        run: |
          cd $MONGODB_DOCKERHUB_REPOSITORY
          docker build -t $DOCKERHUB_ORG/$MONGODB_DOCKERHUB_REPOSITORY:${{ needs.init.outputs.docker_tag }} .
          docker push $DOCKERHUB_ORG/$MONGODB_DOCKERHUB_REPOSITORY:${{ needs.init.outputs.docker_tag }}

      - name: Docker [Postgres]
        run: |
          cd $POSTGRES_DOCKERHUB_REPOSITORY
          docker build -t $DOCKERHUB_ORG/$POSTGRES_DOCKERHUB_REPOSITORY:${{ needs.init.outputs.docker_tag }} .
          docker push $DOCKERHUB_ORG/$POSTGRES_DOCKERHUB_REPOSITORY:${{ needs.init.outputs.docker_tag }}

      - name: Mails
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_GMAIL_USERNAME }}
          password: ${{ secrets.SMTP_GMAIL_PASSWORD }}
          subject: '${{ job.status }}: ${{ github.repository }} » ${{ github.ref_name }}, build # ${{ github.run_number }}'
          to: ${{ secrets.EMAILS_ADMINS }}
          from: Tech1 Ops
          html_body: |
            <b>Status</b>: ${{ job.status }}<br>
            <b>CommitterId</b>: ${{ github.actor }}<br>
            <b>Actions</b>: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}<br>
            <b>Changes</b>: https://github.com/${{ github.repository }}/commit/${{ github.sha }}<br>
            <b>Committer</b>: ${{ github.event.commits[0].committer.name }}<br>
            <b>Message</b>: ${{ github.event.commits[0].message }}<br>
